export const FETCH_PRINTERS_REQUEST = 'FETCH_PRINTERS_REQUEST';
export const FETCH_PRINTERS_SUCCESS = 'FETCH_PRINTERS_SUCCESS';
export const FETCH_PRINTERS_FAILED = 'FETCH_PRINTERS_FAILED';

export const ADD_PRINTER_REQUEST = 'ADD_PRINTER_REQUEST';
export const ADD_PRINTER_SUCCESS = 'ADD_PRINTER_SUCCESS';
export const ADD_PRINTER_FAILED = 'ADD_PRINTER_FAILED';

export const UPDATE_PRINTER_REQUEST = 'UPDATE_PRINTER_REQUEST';
export const UPDATE_PRINTER_SUCCESS = 'UPDATE_PRINTER_SUCCESS';
export const UPDATE_PRINTER_FAILED = 'UPDATE_PRINTER_FAILED';

export const DELETE_PRINTER_REQUEST = 'DELETE_PRINTER_REQUEST';
export const DELETE_PRINTER_SUCCESS = 'DELETE_PRINTER_SUCCESS';
export const DELETE_PRINTER_FAILED = 'DELETE_PRINTER_FAILED';